# Pre-Set Variables.
CC = g++

# Target: Pre-Requisites
#	Command

# @echo prints the string in the command, not the full statement.
build: main
	@echo "Building the game."
	./main

main: main.cpp
	${CC} main.cpp -o main

clean:
	@echo "Cleaning up the files."
	rm -f main